- project:
    check:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/horizon
        - horizon-openstack-tox-py35dj20:
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            required-projects:
              - openstack/horizon
        - horizon-openstack-tox-py35dj20:
            required-projects:
              - openstack/horizon
